app/models.py
from . import db 
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index= True)
    pass_secure= db.Column(db.String(255))
    pitch = db.relationship('Pitches',backref = 'user',lazy = "dynamic")
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password) 

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

class Pitches(db.Model):
    ___tablename__ = 'pitch'

    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    pitch_title = db.Column(db.String)
    pitch_category = db.Column(db.String)
    pitch_content = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    upvote = db.relationship('Upvote',backref='user',lazy='dynamic')
    downvote = db.relationship('Downvote',backref='user',lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,id):
        pitch = Pitches.query.filter_by(pitch_id=id).all()
        return pitch


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    comment = db.Column(db.Text(),nullable = False)
    # pitch_id = db.Column(db.Integer,db.ForeignKey('pitch.id'),nullable = False)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch_id):
        comments = Comment.query.filter_by(pitch_id=pitch_id).all()

        return comments

    
    def __repr__(self):
        return f'comment:{self.comment}'

class Upvote(db.Model):
    __tablename__ = 'upvotes'

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))
    

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_upvotes(cls,id):
        upvote = Upvote.query.filter_by(pitch_id=id).all()
        return upvote


    def __repr__(self):
        return f'{self.user_id}:{self.pitch_id}'
class Downvote(db.Model):
    __tablename__ = 'downvotes'

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))
    

    def save(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_downvotes(cls,id):
        downvote = Downvote.query.filter_by(pitch_id=id).all()
        return downvote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField,SelectField, SubmitField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    category = SelectField('Category', choices=[('Pickup_lines','Pickup_lines'),('Product','Product'),('Promotion','Promotion')],validators=[Required()])
    title = StringField('Pitch title',validators=[Required()])
    content = TextAreaField('Pitch content', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    title = StringField('title',validators=[Required()])
    comment = TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask import Flask
from config import config_options
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect
from flask_mail import Mail


mail = Mail()
csrf = CSRFProtect()
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)

    # creating app configurations
    app.config.from_object(config_options[config_name])
    app.config['SECRET_KEY'] = 'snskdcjkl5jksclc9'

    # registering blueprints
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)
    mail.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required, current_user
from . import main
from .. import db
from .forms import PitchForm, CommentForm, UpdateProfile
from ..models import Pitches,Comment,User

@main.route('/')
def index():
    pitches = Pitches.query.all()
    promotion = Pitches.query.filter_by(pitch_category = 'Promotion').all() 
    pickup = Pitches.query.filter_by(pitch_category = 'Pickup-lines').all()
    product = Pitches.query.filter_by(pitch_category = 'Product').all()
    return render_template('index.html', promotion = promotion,pickup = pickup ,product = product, pitches = pitches)

    # return render_template('index.html')

@main.route('/pitch', methods = ['GET', 'POST'])
@login_required
def pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title= form.title.data
        category = form.category.data
        content = form.content.data

        new_pitch = Pitches(pitch_title=title,pitch_category= category, pitch_content= content, user= current_user)

        new_pitch.save_pitch()
        return redirect(url_for('.index'))

    return render_template('pitch.html' ,pitch_form= form)

@main.route('/comments/<pitch_id>', methods = ['GET', 'POST'])
@login_required
def comment(pitch_id):
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = comment_form.comment.data 
        pitch_id = pitch_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment = comment,user_id = user_id,pitch_id = pitch_id)
        new_comment.save_comment()
        return redirect(url_for('.index'))
    return render_template('comment.html', comment_form =comment_form)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/like/<int:id>',methods = ['POST','GET'])
@login_required
def like(id):
    get_pitches = Upvote.get_upvotes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.index',id=id))
        else:
            continue
    new_vote = Upvote(user = current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.index',id=id))

@main.route('/dislike/<int:id>',methods = ['POST','GET'])
@login_required
def dislike(id):
    pitch = Downvote.get_downvotes(id)
    valid_string = f'{current_user.id}:{id}'
    for p in pitch:
        to_str = f'{p}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.index',id=id))
        else:
            continue
    new_downvote = Downvote(user = current_user, pitch_id=id)
    new_downvote.save()
    return redirect(url_for('main.index',id = id))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!--  -->



<!-- Navbar block -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<body style=" background-repeat:no-repeat; background-size:cover; 
background-image:url('https://cdn.pixabay.com/photo/2015/07/02/10/13/sky-828648_960_720.jpg'); color:white;">
    
    <div class="container">
    <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-8">
    
    {{wtf.quick_form(comment_form)}}
    
    </div>
    <div class="col-md-2"></div>
    </div>
    </div>
</body>

{% endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}


    {% block content%}
        <div  class="container">
                <h2 class="text-center" style="color:white;">Pitches</h2>
            <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
                <li class="nav-item" >
                    <a id ="cats" class="nav-link" data-toggle="tab" href="#pitch"><strong>All Pitches</strong> </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link"  data-toggle="tab" href="#promotion">Promotion Pitches</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#product">Product Pitches</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#pick">Pickup-Lines Pitches</a>
                </li>
            </ul>
        </div>
            <div class="tab-content">
                <div  class="container tab-pane active" id="pitch"><br>
                    {{ macro.display(pitches) }}
                </div>
                <div id="product" class="container tab-pane fade"><br>
                    {{ macro.display(product)}}
                </div>
                <div  id="promotion" class="container tab-pane fade"><br>
                    {{ macro.display(promotion) }}
                </div>
                <div id="pick" class="container tab-pane fade"><br>
                    {{ macro.display(pickup) }}
                    
                </div>
            </div>
        </div>
{% endblock%}

app/templates/macros.html
{% macro display(pitches) %}
<body style=" background-repeat:no-repeat; background-size:cover; 
background-image:url('https://cdn.pixabay.com/photo/2015/07/02/10/13/sky-828648_960_720.jpg');">
    <div class="container-fluid">
		<div class="row">
            {% for categ in pitches %}
            <div class="col-md-3" style=" margin-left: 20px; padding: 20px;
            margin-bottom: 20px; border:none; font-size: 15px; width: 40%; ">
                <div class="thumbnail" style="height:100%;">
                    <h3>{{categ.pitch_title}}</h3>
                    <hr>
                    <div class="card-body">
                        <p><i>{{categ.pitch_content}}<i></p>
                        <p><b>Category:</b>{{categ.pitch_category}}</p>
                        <footer class="blockquote-footer"><b>Posted by:</b> {{categ.user.username}}</footer>
                        <hr>
                        <span class="foot" > <a href="{{url_for('main.like',id = categ.id)}}"><i class="fa fa-thumbs-up" style="font-size:18px;color: green"></i></a> {{categ.upvote.count()}}</span>
                        <span class="foot"> <a href="{{url_for('main.dislike',id = categ.id)}}"> <i class="fa fa-thumbs-down" style="color:red;"></i> {{categ.downvote.count()}}</a></span></div>
									
                        
            <a href="{{url_for('.comment',pitch_id = categ.id)}}" class="btn btn-primary btn-sm"> Comment</a>

        </div>
    </div>
</div>
{% endfor %}
</div>
</div>
{% endmacro %}

</body>
    

app/templates/navbar.html
  <div class="navbar navbar-inverse" role="navigation" style="background-color:black; border:none; font-size:18px;">
    <div class="container-fluid">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('main.pitch')}}">PostPitch</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Log out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Log In</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</div>

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<body style=" background-repeat:no-repeat; background-size:cover; 
background-image:url('https://cdn.pixabay.com/photo/2015/07/02/10/13/sky-828648_960_720.jpg'); color:white;">
    <div class="container">
        <div class="row">
            <div class="col-md-2"> </div>
            <div class="col-md-8" style="width:50%; height:400px; margin-top:30px; padding:50px; background-color:rgba(0, 0, 0, 0.8);">
            
            {{wtf.quick_form(pitch_form)}}
            
            </div>
            <div class="col-md-2"></div>
            </div>
    </div>
</body>
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<body style=" background-repeat:no-repeat; background-size:cover; 
background-image:url('https://cdn.pixabay.com/photo/2015/07/02/10/13/sky-828648_960_720.jpg'); color:white;">
    <div class="container">
        <div class="row">
        <!-- displaying  Username-->
            <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>
        
            <!--Displaying user bio-->
            {% if user.bio %}
                <p> {{user.bio}}</p>
            {%else%}
                <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
            </div>
        
            <!--Display profile photo-->
            <div class="col-md-4">
        
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
            </div>
        </div>
            </div>  
</body>

{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<body style=" background-repeat:no-repeat; background-size:cover; 
background-image:url('https://cdn.pixabay.com/photo/2015/07/02/10/13/sky-828648_960_720.jpg'); color:white;">
    <div class="container">
        {{wtf.quick_form(form)}}
    </div>
</body>

{% endblock %}